name: blackhole_spliter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: any
  flutter_svg: any
  get: ^4.6.5
  lottie: ^2.3.2
  flutter_blue_plus: ^1.15.8
  permission_handler: ^11.0.0
  get_it: ^7.6.4
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_downloader: ^1.11.6
  path_provider: ^2.1.2
  youtube_downloader: ^0.0.6
  # http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
